on: [push, pull_request]

name: CI

jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node: [ '14', '16' ]
        name: Node ${{ matrix.node }} Testing
        steps:
            - uses: actions/checkout@v3
            - name: Setup NodeJS
              uses: actions/setup-node@v2
              with:
                  node-version: ${{ matrix.node }}
            - run: npm install
            - run: npm test
            - run: npm audit --production
